---
abstract: 'A simple lightweight OpenID consumer with very few dependencies'
author:
  - 'Holger Eiboeck <realholgi@cpan.org>'
build_requires:
  CGI: 0
  Test::Mock::LWP::Dispatch: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OpenID-Login
requires:
  Carp: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Moose: 0.51
  Moose::Util::TypeConstraints: 0
  URI: 0
  URI::Escape: 0
  strict: 0
resources:
  homepage: http://github.com/realholgi/OpenID-Login
  repository: git://github.com/realholgi/OpenID-Login.git
version: 0.1.2
